[env:gamingboard]
extends = nrf52840_base
board = promicro-nrf52840
build_flags = ${nrf52840_base.build_flags}
  -Ivariants/gamingboard
  -DPRIVATE_HW
  -L"${platformio.libdeps_dir}/${this.__env__}/bsec2/src/cortex-m4/fpv4-sp-d16-hard"
  -DGAMING_THINGS=1                   ; Flag for enabling display (why not use USE_EINK?)
  -DMESHTASTIC_EXCLUDE_GPS=1          ; Don't need native GPS
  -DMESHTASTIC_EXCLUDE_SERIAL=1       ; Don't need serial output
  -DEINK_DISPLAY_MODEL=GxEPD2_154_D67 ; Waveshare 1.54in B/W display
  -DEINK_WIDTH=200
  -DEINK_HEIGHT=200
  -DUSE_EINK_DYNAMICDISPLAY           ; Enable Dynamic EInk
  -DEINK_LIMIT_FASTREFRESH=10         ; How many consecutive fast-refreshes are permitted
  -DEINK_LIMIT_RATE_BACKGROUND_SEC=30 ; Minimum interval between BACKGROUND updates
  -DEINK_LIMIT_RATE_RESPONSIVE_SEC=1  ; Minimum interval between RESPONSIVE updates
  -DEINK_BACKGROUND_USES_FAST         ; (Optional) Use FAST refresh for both BACKGROUND and RESPONSIVE, until a limit is reached.

build_src_filter = ${nrf52840_base.build_src_filter} +<../variants/gamingboard> -<modules/SerialModule.cpp>

lib_deps = 
  ${nrf52840_base.lib_deps}
  https://github.com/meshtastic/GxEPD2#master
